name: Unit Test on Pull Request

on: 
  workflow_dispatch:
  pull_request_target:
    types: [labeled]


jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Test
      run: Invoke-Pester